### ISSUE TITLE
3.0.0 crashing when trying to export with .skl

### ISSUE THREAD

**Issue by APPenchev** [Crauzer/lol2gltf#26]
I was trying to export a skin with the UI version of 3.0.0 beta 5, but it keeps crashing if I export with .skl. 
Note: I have tested this on multiple skins and it only happens on some of them.

![renecbug](https://user-images.githubusercontent.com/36088861/216770080-dd669d0f-67b8-43c0-9ac6-127ee6ddb2fe.gif)

**Comment by Crauzer** [comment]
Can you check if this also happens on beta.6 ?
https://github.com/Crauzer/lol2gltf/releases/tag/3.0.0-beta.6

**Comment by APPenchev** [comment]
Yes, this issue is present in beta 4 and 6 aswell.

![renecbug2](https://user-images.githubusercontent.com/36088861/216773607-7c3f1d45-6530-4c4c-b5c8-bba3bb00d8ae.gif)

**Comment by Crauzer** [comment]
I took a quick peek at the files you're trying to convert while fixing some other bug.
It seems like the skeleton contains joints which have the same values of their hashed name. This is causing a crash because the conversion process relies on identifying joints by their name hash so I will need to take a deeper look into this.
![image](https://user-images.githubusercontent.com/18646077/216794026-206bac39-9173-44aa-a8d3-910fcd9aa7e7.png)

**Comment by Crauzer** [comment]
fixed in https://github.com/Crauzer/lol2gltf/commit/70b62bf772288c1c99c3b2720d5d2b0ca12ee794
